# Generated by Django 4.0.1 on 2022-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='JobNotes.Vehicle'),
        ),
    ]
