# Generated by Django 4.0.1 on 2022-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0002_alter_job_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='equipment',
        ),
        migrations.AddField(
            model_name='job',
            name='Equipment',
            field=models.CharField(default='vac-hose', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='job',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='job',
            name='vehicles',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.IntegerField(default='5'),
            preserve_default=False,
        ),
    ]
