# Generated by Django 4.0.1 on 2022-01-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0003_remove_job_equipment_job_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Equipment',
            new_name='equipment',
        ),
    ]
