# Generated by Django 4.0.1 on 2022-01-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0005_job_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='active',
            new_name='my_jobs',
        ),
    ]
