# Generated by Django 4.0.1 on 2022-01-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0008_task_description_alter_task_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timein',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.TimeField(blank=True),
        ),
    ]
