# Generated by Django 4.0.1 on 2022-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0010_alter_task_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.TimeField(null=True),
        ),
    ]
