# Generated by Django 4.0.1 on 2022-01-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0012_alter_task_name_alter_task_timein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
