# Generated by Django 4.0.1 on 2022-01-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0013_alter_task_timein_alter_task_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timeout',
        ),
    ]
