# Generated by Django 4.0.1 on 2022-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0014_remove_task_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
