# Generated by Django 4.0.1 on 2022-01-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0015_task_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.TimeField(blank=True, default='12:00', null=True),
        ),
    ]
