# Generated by Django 4.0.1 on 2022-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0017_alter_task_timein_alter_task_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
