# Generated by Django 4.0.1 on 2022-01-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0019_alter_equipment_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='my_jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='active_jobs',
            field=models.ManyToManyField(related_name='active_jobs', to='JobNotes.Active'),
        ),
    ]
