# Generated by Django 4.0.1 on 2022-02-12 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0021_taskmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active_jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 12)),
        ),
        migrations.RemoveField(
            model_name='job',
            name='equipment',
        ),
        migrations.AddField(
            model_name='job',
            name='equipment',
            field=models.ManyToManyField(related_name='equipment_used', to='JobNotes.Equipment'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='job',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='JobNotes.Vehicle'),
        ),
        migrations.DeleteModel(
            name='Active',
        ),
    ]
