# Generated by Django 4.0.1 on 2022-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotes', '0022_remove_job_active_jobs_job_active_alter_job_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workers', to='JobNotes.User'),
        ),
    ]
